@startuml

skinparam groupInheritance 2
skinparam ClassFontSize 18
skinparam classAttributeIconSize 0

class csc1061.ch24.MyPriorityQueue #SpringGreen {
  -csc1061.ch24.MyHeap<E> : heap
  +MyPriorityQueue()
  +getSize() : int
  +enqueue(e : E)
  +dequeue() : E
}

@enduml